# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 615f298c91fbb8c587c12110de685d392532e91a75fe712f2379fad45c45dc1dcb6a171994374594a47d444f7e7867ed3fa7b6a50b4c12ede3d301f842f90a5c

test:
  secret_key_base: ee2574bc26be86b9fbd363fac294ebb6c0a880c2523ad944388eebac1ab226eeb78a91715e569e5afdbd66ff97132b06d5145542db42efd78cd961d64476d75e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
